### ISSUE TITLE
How to interpret "Free a" to return "b"?

### ISSUE THREAD

**Issue by ildar-shaymukhametov** [graninas/Pragmatic-Type-Level-Design#1]
![image](https://github.com/graninas/Pragmatic-Type-Level-Design/assets/74532770/cf332677-e862-40f7-92e0-80e70063d0a5)
![image](https://github.com/graninas/Pragmatic-Type-Level-Design/assets/74532770/471294fe-8bc4-4332-a521-574c298831df)
I want to interpret the language differently (to return "String" instead of "Number")
But I cannot understand how to do it?
It it even possible?
Or do other interpreters always have to return the same type "Number"?
If so, what is the point of different interpreters?

**Comment by graninas** [comment]
Hi @ildar-shaymukhametov , I just discovered your question. Is it still actual? Do you need me to answer it?
